apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-cluster-binding
  namespace: default
roleRef:
  kind: ClusterRole
  name: admin-cluster
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: admin-cluster
  apiGroup: rbac.authorization.k8s.io
