apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: basic-binding
  namespace: default
subjects:
- kind: User
  name: basic
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: basic
  apiGroup: rbac.authorization.k8s.io
