apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-binding
roleRef:
  kind: Role
  name: dev
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: dev
  apiGroup: rbac.authorization.k8s.io