apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: sc-backend-deployment 
  labels: 
    app: sc-backend 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: sc-backend 
  template: 
    metadata: 
      labels: 
        app: sc-backend 
    spec: 
      containers: 
      - name: sc-backend-container 
        image: localhost:32000/syl/sc2:registry 
        ports: 
        - containerPort: 3000 
