apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: sc-deployment 
  labels: 
    app: sc 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: sc 
  template: 
    metadata: 
      labels: 
        app: sc 
    spec: 
      containers: 
      - name: sc-container 
        image: localhost:32000/syl/sc:registry 
        ports: 
        - containerPort: 3000
